// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class Book;
@class BookBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface BookRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Book : PBGeneratedMessage {
@private
  BOOL hasPageNumber_:1;
  BOOL hasBookId_:1;
  BOOL hasTitle_:1;
  SInt32 pageNumber;
  NSString* bookId;
  NSString* title;
}
- (BOOL) hasBookId;
- (BOOL) hasTitle;
- (BOOL) hasPageNumber;
@property (readonly, strong) NSString* bookId;
@property (readonly, strong) NSString* title;
@property (readonly) SInt32 pageNumber;

+ (Book*) defaultInstance;
- (Book*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BookBuilder*) builder;
+ (BookBuilder*) builder;
+ (BookBuilder*) builderWithPrototype:(Book*) prototype;
- (BookBuilder*) toBuilder;

+ (Book*) parseFromData:(NSData*) data;
+ (Book*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Book*) parseFromInputStream:(NSInputStream*) input;
+ (Book*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Book*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Book*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BookBuilder : PBGeneratedMessageBuilder {
@private
  Book* result;
}

- (Book*) defaultInstance;

- (BookBuilder*) clear;
- (BookBuilder*) clone;

- (Book*) build;
- (Book*) buildPartial;

- (BookBuilder*) mergeFrom:(Book*) other;
- (BookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBookId;
- (NSString*) bookId;
- (BookBuilder*) setBookId:(NSString*) value;
- (BookBuilder*) clearBookId;

- (BOOL) hasTitle;
- (NSString*) title;
- (BookBuilder*) setTitle:(NSString*) value;
- (BookBuilder*) clearTitle;

- (BOOL) hasPageNumber;
- (SInt32) pageNumber;
- (BookBuilder*) setPageNumber:(SInt32) value;
- (BookBuilder*) clearPageNumber;
@end


// @@protoc_insertion_point(global_scope)
